services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"